apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: sonarqube
  name: service-public-sonarqube
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: ci
spec:
  type: LoadBalancer # <- Creates AWS Classic Load Balancer
  selector:
    app: sonarqube
    release: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80