apiVersion: v1
kind: Service
metadata:
  namespace: ci
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: sonarqube
  name: np-sonarqube
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: ci
spec:
  type: NodePort # <- Creates AWS Classic Load Balancer
  selector:
    app: sonarqube
    release: sonarqube
  ports: 
  - port: 9000
    protocol: TCP
    targetPort: 9000